import { JobPosting } from '~/types';

const careerOpportunities: JobPosting[] = [
  {
    id: '1',
    title: 'Automation Test Engineer (JavaScript/TypeScript)',
    type: 'Fulltime',
    location: 'Ho Chi Minh',
    skills: [
      'Automation Test',
      'Git',
      'Java',
      'Playwright',
      'TypeScript',
      'JavaScript',
    ],
    expertise: 'Automation Tester',
    topReasons: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    description: [
      'Write scenarios for system screens / functions',
      'Develop and maintain automation test scripts.',
      'Run CI / Test scripts',
      'Bug analysis',
      'Monitor and report on test results using Report Portal.',
      'Active approach technological challenges and sharing the knowledge for the organization',
    ],
    compensation: '1,000-2000$',
    skillsRequired: {
      must: [
        'Willingness to develop and improve services with a sense of ownership',
        'Experience writing scenarios for system screens / functions',
        'Experience developing with JavaScript/TypeScript from total 2 years+',
        'Experience with Playwright for automation testing (1 year+)',
        'Experience with CI/CD tools, specifically GitHub Actions (1 year+)',
        'Experience working with databases (1 year+).',
        'Experience developing in a team using Git',
        'Experience in manual testing',
        'Experience in bug analysis',
      ],
      preferable: [
        'Experience working with Autify',
        'Experience working with Sikuli',
        'Experience in designing and implementing CI/CD pipelines.',
        'Experience in programming languages such as Java',
        'Familiarity with collaboration tools like Microsoft Teams.',
        'Familiarity with testing management and issue tracking tools like Report Portal.',
        'Good communication skills and the ability to work effectively in a team environment.',
      ],
    },
    whyJoinUs: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    benefits: [
      'Annual Leave: 15 days/ year',
      'Flexible Working Time (Hybrid Working)',
      '100% Salary in Probation',
      'Salary Review (Twice a Year)',
      '13th Salary bonus',
      'Social Insurance for 100% Salary',
      'Travel Allowance',
      'Premium Health Care Insurance for employees (PTI)',
      'Annual Health Check',
      'Device Full Provide',
      'Monthly Happy Hour, Company Trip, Year End Party and Events',
      'Marriage / Baby Gift',
      'Funeral Expenses',
      'Referral Bonus',
      'Skill Improvement Course for Employees (Udemy)',
    ],
    officeLocation:
      '6th Floor An Phu Plaza, 117-119 Ly Chinh Thang, Xuan Hoa Ward, Ho Chi Minh.',
    applyEmail: 'careers@example.com',
  },
  {
    id: '2',
    title: 'C# Leader Developer (.NET)',
    type: 'Fulltime',
    location: 'Ho Chi Minh',
    skills: ['C#', 'Git', 'ASP.NET', 'API', 'Leadership', '.NET'],
    expertise: 'Software/Technical Architect',
    topReasons: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    description: [
      'Development team Tech lead or member Management',
      'Overall maintenance and development of core systems (design to release/back-end and front-end development)',
      'Implementation of various deliverable reviews such as design and source code of development members (final quality check)',
      'Implementation of system architecture improvement activities',
      'Proactively take on technical challenges and actively return knowledge to the organization',
    ],
    compensation: '2,000-2750$',
    skillsRequired: {
      must: [
        'More than + years experience as a leader',
        'Development experience of Web API (REST) using ASP.NET Core and C#',
        'RDBMS knowledge and development experience',
        'Knowledge and usage experience of any frameworks such as Angular, React, Vue.js, etc. and Typescript',
        'Experience creating unit tests',
        'Development experience in a team using Git',
        'Good knowledge of database tuning',
      ],
      preferable: [
        'Experience in using and building cloud environments such as Azure Devops',
        'Team building experience',
        'Scrum development experience',
      ],
    },
    whyJoinUs: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    benefits: [
      'Annual Leave: 15 days/ year',
      'Flexible Working Time (Hybrid Working)',
      '100% Salary in Probation',
      'Salary Review (Twice a Year)',
      '13th Salary bonus',
      'Social Insurance for 100% Salary',
      'Travel Allowance',
      'Premium Health Care Insurance for employees (PTI)',
      'Annual Health Check',
      'Device Full Provide',
      'Monthly Happy Hour, Company Trip, Year End Party and Events',
      'Marriage / Baby Gift',
      'Funeral Expenses',
      'Referral Bonus',
      'Skill Improvement Course for Employees (Udemy)',
    ],
    officeLocation:
      '6th Floor An Phu Plaza, 117-119 Ly Chinh Thang, Xuan Hoa Ward, Ho Chi Minh.',
    applyEmail: 'careers@example.com',
  },
  {
    id: '3',
    title: 'Middle/Senior Back End Developer (Java)',
    type: 'Fulltime',
    location: 'Ho Chi Minh',
    skills: ['Java', 'Spring Boot', 'MVC', 'Spring', 'JavaScript', 'SQL'],
    expertise: 'Backend Developer',
    topReasons: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    description: [
      'Developing and implementing features relevant to Backend side with Agile Scrum Methodology',
      'Maintaining and improving performance of existing systems with flexible solutions.',
      'Modifying and refactoring according to changing business requirements.',
      'Implementing high-quality software with automation testing.',
      'Open-minded newly with many interesting tools and libraries.',
      'Self-improvement with huge technical documents and sharing, coaching presentations.',
      'For senior level: Support Lead Backend Developer to manage junior/fresher',
    ],
    compensation: '1,000-2000$',
    skillsRequired: {
      must: [
        'This level able to develop under the direction of the Lead Engineer',
        'Willingness to develop and improve services with the sense of ownership',
        'Experience development web application using Java from 3 years (exclude training period)',
        'Experience with Spring Boot, Spring MVC',
        'Basic knowledge and experience with SQL',
        'Experience in team development with using Git',
        'Experience in development performance-oriented DML',
        'Experience in development DDL',
        'Experience in designing APIs based on the OpenAPI specification',
      ],
      preferable: [
        'Experience with UI library/framework such as React',
        'Experience with PHP',
        'Knowledge of basic security issues such as SQL injection, XSS, CSRF, etc',
        'Experience with web application development using cloud service such as AWS',
        'Experienced in team building',
        'Experience with Scrum development',
        'Basic knowledge and experience with Clean Architecture',
      ],
    },
    whyJoinUs: [
      'Hybrid Working style and Flexible working time',
      'Competitive salary, bonus, expenses and allowances',
      '15 days of paid leave + Health Care Insurance',
    ],
    benefits: [
      'Annual Leave: 15 days/ year',
      'Flexible Working Time (Hybrid Working)',
      '100% Salary in Probation',
      'Salary Review (Twice a Year)',
      '13th Salary bonus',
      'Social Insurance for 100% Salary',
      'Travel Allowance',
      'Premium Health Care Insurance for employees (PTI)',
      'Annual Health Check',
      'Device Full Provide',
      'Monthly Happy Hour, Company Trip, Year End Party and Events',
      'Marriage / Baby Gift',
      'Funeral Expenses',
      'Referral Bonus',
      'Skill Improvement Course for Employees (Udemy)',
    ],
    officeLocation:
      '6th Floor An Phu Plaza, 117-119 Ly Chinh Thang, Xuan Hoa Ward, Ho Chi Minh.',
    applyEmail: 'careers@example.com',
  },
];

export default careerOpportunities;
